parameters:
  - name: TargetOS
    type: object
    default:
      - 19H1
  - name: Platform
    type: object
    default:
      - x64
      - arm64
  - name: Configuration
    type: object
    default:
      - Release
      - Debug

jobs:
- job: build
  displayName: 'Build'
  pool:
    name: 'Azure - SW Build EWDK Agents'
  workspace:
    clean: all
  strategy:
    maxParallel: 3
    matrix:
      ${{ each t in parameters.TargetOS }}:
        ${{ each c in parameters.Configuration }}:
          ${{ each p in parameters.Platform }}:
            ${{t}}_${{c}}_${{p}}:
              TargetOS: ${{t}}
              Platform: ${{p}}
              Configuration: ${{c}}
  
  steps:
  - powershell: .\build.ps1 -TargetOS $Env:TARGETOS -Configuration $Env:Configuration -Platform $Env:Platform
    displayName: 'Build $(TargetOS)-$(Configuration)-$(Platform)'
  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'Bin_$(TargetOS)_$(Configuration)_$(Platform)'
      targetPath: '$(Build.SourcesDirectory)/$(Configuration)/$(Platform)'
      
